#spring.application.name=booting-web
#server.port=8000
############################################
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8000
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 9000
